<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nodoraiz [
	<!ELEMENT nodoraiz (elemento1, elemento2*)>
	<!ELEMENT elemento1 (#PCDATA)>
	<!ELEMENT elemento2 (#PCDATA)>
	
	<!-- 
		Referencia a varios IDs existentes
	-->
	<!ATTLIST elemento2 at1 ID #REQUIRED>
	<!ATTLIST elemento2 at2 IDREFS #IMPLIED>
]>
<nodoraiz>
	<elemento1></elemento1>
	<elemento2 at1="id1"></elemento2>
	<elemento2 at1="id2"></elemento2>
	<elemento2 at1="otro" at2="id1 id2"></elemento2>
</nodoraiz>
	